### PR TITLE
Prevent redundant autoloader registerations. Fixes #304

### LINKED ISSUE #302: Provider for Silex v2
https://github.com/bobthecow/mustache-silex-provider seems to have issues disabled, so opening one here.

Seems to hard require Silex v1, so doesn't work with v2.

Any plans to update? I could look into changes and possibly PR.

### LINKED ISSUE #304: Autoloader should protect against registering multiple loaders
As Mustache_Autoloader exists, it is possible to register the autoloader multiple times.

for instance:

```php
<?php

require __DIR__ . '/mustache.php/src/Mustache/Autoloader.php';

for ($i = 0; $i < 10; $i++) {
    Mustache_Autoloader::register();
    echo "Number of Mustache autoloaders ".count(spl_autoload_functions())."\n";
}
```

ouputs:

```
Number of Mustache autoloaders 1
Number of Mustache autoloaders 2
Number of Mustache autoloaders 3
Number of Mustache autoloaders 4
Number of Mustache autoloaders 5
Number of Mustache autoloaders 6
Number of Mustache autoloaders 7
Number of Mustache autoloaders 8
Number of Mustache autoloaders 9
Number of Mustache autoloaders 10
```

### PR DESCRIPTION
**Pull request by hcpss-banderson**

### CODE REVIEW

File: src/Mustache/Autoloader.php [hunk 1]
```diff
@@ -15,6 +15,14 @@
...
 {
     private $baseDir;
+    
+    /**
+     * An array where the key is the baseDir and the key is an instance of this
+     * class.
+     * 
+     * @var array
+     */
+    static private $_instances;
```
Comment (bobthecow) [inline src/Mustache/Autoloader.php]: Please drop the `_` prefix on the variable name.

**Comment by hcpss-banderson** [comment]
I've updated the branch to dev and removed the "_".
